# Database persistence type.
conductor.db.type=postgres
conductor.queue.type=postgres
conductor.external-payload-storage.type=postgres

# External context path.
server.servlet.context-path=/conductor

# Database connectivity.
spring.datasource.url=jdbc:postgresql://postgresdb:5432/postgres
spring.datasource.username=conductor
spring.datasource.password=conductor

# Indexing properties.
conductor.indexing.enabled=true
conductor.indexing.type=postgres
conductor.elasticsearch.version=0

# Health and metrics.
conductor.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=health,prometheus

# Load sample kitchen-sink workflow.
loadSample=true

# Shorten postpone duration to speed up concurrent execution limit tests.
conductor.app.taskExecutionPostponeDuration=10s
